In [35]:
import pandas as pd
import numpy as np

In [36]:
df=pd.read_csv("Historical Data/HBL.csv")
df.head()

Unnamed: 0          TIME    OPEN    HIGH    LOW   CLOSE   VOLUME
0           0  Jan 31, 2018  194.89  197.45  191.5  194.02  2641700
1           1  Jan 30, 2018  204.20  205.48  194.2  195.55  3056400
2           2  Jan 29, 2018  206.00  209.00  201.0  203.53  1239200
3           3  Jan 26, 2018  208.10  208.10  200.1  201.90  1368400
4           4  Jan 25, 2018  210.10  211.00  208.0  208.68   569600

In [37]:
df.shape

(1119, 7)

In [38]:
features=df["TIME"]
target=df["HIGH"]

In [39]:
features.shape,target.shape

((1119,), (1119,))

In [40]:
features.head()

0    Jan 31, 2018
1    Jan 30, 2018
2    Jan 29, 2018
3    Jan 26, 2018
4    Jan 25, 2018
Name: TIME, dtype: object

In [41]:
target.head()

0    197.45
1    205.48
2    209.00
3    208.10
4    211.00
Name: HIGH, dtype: float64

In [42]:
month=[]
date=[]
year=[]
tmp=0
for index, item in enumerate(features):
    month.append(features[index][0:3])
    year.append(float(features[index][8:12]))

    if "," in features[index][4:6]:
        tmp=int(features[index][4:5])
    else:
        tmp=int(features[index][4:6])
    date.append(tmp)

In [43]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
month_en=encoder.fit_transform(month)
month_en

array([4, 4, 4, ..., 5, 5, 5], dtype=int64)

In [44]:
feat=[]
feat.clear()
for index, item in enumerate(features):
    feat.append([int(month_en[index]),tmp,int(features[index][7:12])])

In [45]:
feat[0:5]

[[4, 1, 2018], [4, 1, 2018], [4, 1, 2018], [4, 1, 2018], [4, 1, 2018]]

In [46]:
len(feat)

1119

In [47]:
encoder.inverse_transform([month_en[0]])

array(['Jan'], dtype='<U3')

In [48]:
type(target),type(feat)

(pandas.core.series.Series, list)

In [49]:
year[0:5],target[0:5]

([2018.0, 2018.0, 2018.0, 2018.0, 2018.0],
 0    197.45
 1    205.48
 2    209.00
 3    208.10
 4    211.00
 Name: HIGH, dtype: float64)

In [50]:
target=list(target)

In [51]:
feat_np=np.array(feat)
target_np=np.array(target)

In [52]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(feat,target,test_size=0.2)
len(x_train),len(x_test)

(895, 224)

# DL models

-----------------------------------

In [53]:
from keras import models,layers
DL_model=models.Sequential()
DL_model.add(layers.Dense(64, activation="relu"))
DL_model.add(layers.Dense(128, activation="relu"))
DL_model.add(layers.Dense(256, activation="relu"))
DL_model.add(layers.Dense(512, activation="relu"))
DL_model.add(layers.Dense(1024, activation="relu"))
DL_model.add(layers.Dense(2048, activation="relu"))
DL_model.add(layers.Dense(4096, activation="relu"))
DL_model.add(layers.Dense(1))


In [54]:
DL_model.compile(optimizer="adam",loss="mae",metrics=["mae"])

In [55]:
DL_model.fit(feat_np,target_np,epochs=20,validation_split=0.15)

Epoch 1/20
30/30 [==============================] - 8s 213ms/step - loss: 67.5020 - mae: 67.5020 - val_loss: 34.4204 - val_mae: 34.4204
Epoch 2/20
30/30 [==============================] - 5s 167ms/step - loss: 21.2892 - mae: 21.2892 - val_loss: 32.1147 - val_mae: 32.1147
Epoch 3/20
30/30 [==============================] - 5s 157ms/step - loss: 21.4148 - mae: 21.4148 - val_loss: 13.0056 - val_mae: 13.0056
Epoch 4/20
30/30 [==============================] - 6s 192ms/step - loss: 22.3270 - mae: 22.3270 - val_loss: 8.5266 - val_mae: 8.5266
Epoch 5/20
30/30 [==============================] - 6s 208ms/step - loss: 21.5380 - mae: 21.5380 - val_loss: 9.7980 - val_mae: 9.7980
Epoch 6/20
30/30 [==============================] - 6s 195ms/step - loss: 23.8067 - mae: 23.8067 - val_loss: 33.9856 - val_mae: 33.9856
Epoch 7/20
30/30 [==============================] - 6s 191ms/step - loss: 22.9454 - mae: 22.9454 - val_loss: 20.1042 - val_mae: 20.1042
Epoch 8/20
30/30 [==============================] - 

In [56]:
feat[-1],target[-1]

([5, 1, 2022], 91.98)

In [57]:
sample=[[int(encoder.transform(["Jul"])),7,2022]]

In [58]:
DL_model.predict(sample)

1/1 [==============================] - 0s 255ms/step


array([[132.65765]], dtype=float32)

# ML Models

------------------------------------------------------

In [59]:
from sklearn.linear_model import LinearRegression
ML_model=LinearRegression()
ML_model.fit(x_train,y_train)

LinearRegression()

In [60]:
ML_model.score(x_test,y_test)

0.35202855088099716

In [61]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test,ML_model.predict(x_test))

15.786135042015086

In [62]:
ML_model.predict(sample)

array([108.25367914])

In [63]:
from sklearn.tree import DecisionTreeRegressor
DT_model=DecisionTreeRegressor()
DT_model.fit(x_train,y_train)

DecisionTreeRegressor()

In [64]:
DT_model.score(x_test,y_test)

0.9127360330498595

In [65]:
mean_absolute_error(y_test,DT_model.predict(x_test))

4.297687988313348

In [66]:
DT_model.predict(sample)

array([92.214])