In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("Historical Data/HBL.csv")
df.head()

Unnamed: 0          TIME    OPEN    HIGH    LOW   CLOSE   VOLUME
0           0  Jan 31, 2018  194.89  197.45  191.5  194.02  2641700
1           1  Jan 30, 2018  204.20  205.48  194.2  195.55  3056400
2           2  Jan 29, 2018  206.00  209.00  201.0  203.53  1239200
3           3  Jan 26, 2018  208.10  208.10  200.1  201.90  1368400
4           4  Jan 25, 2018  210.10  211.00  208.0  208.68   569600

In [3]:
df.shape

(1119, 7)

In [4]:
features=df["TIME"]
target=df["HIGH"]

In [5]:
features.shape,target.shape

((1119,), (1119,))

In [6]:
features.head()

0    Jan 31, 2018
1    Jan 30, 2018
2    Jan 29, 2018
3    Jan 26, 2018
4    Jan 25, 2018
Name: TIME, dtype: object

In [7]:
target.head()

0    197.45
1    205.48
2    209.00
3    208.10
4    211.00
Name: HIGH, dtype: float64

In [8]:
month=[]
date=[]
year=[]
tmp=0
for index, item in enumerate(features):
    month.append(features[index][0:3])
    year.append(float(features[index][8:12]))

    if "," in features[index][4:6]:
        tmp=int(features[index][4:5])
    else:
        tmp=int(features[index][4:6])
    date.append(tmp)

In [9]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
month_en=encoder.fit_transform(month)
month_en

array([4, 4, 4, ..., 5, 5, 5], dtype=int64)

In [10]:
feat=[]
feat.clear()
for index, item in enumerate(features):
    feat.append([int(month_en[index]),tmp,int(features[index][7:12])])

In [11]:
feat[0:5]

[[4, 1, 2018], [4, 1, 2018], [4, 1, 2018], [4, 1, 2018], [4, 1, 2018]]

In [12]:
len(feat)

1119

In [13]:
encoder.inverse_transform([month_en[0]])

array(['Jan'], dtype='<U3')

In [14]:
type(target),type(feat)

(pandas.core.series.Series, list)

In [15]:
year[0:5],target[0:5]

([2018.0, 2018.0, 2018.0, 2018.0, 2018.0],
 0    197.45
 1    205.48
 2    209.00
 3    208.10
 4    211.00
 Name: HIGH, dtype: float64)

In [16]:
target=list(target)

In [17]:
feat_np=np.array(feat)
target_np=np.array(target)

In [18]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(feat,target,test_size=0.2)
len(x_train),len(x_test)

(895, 224)

In [19]:
from keras import models,layers
DL_model=models.Sequential()
DL_model.add(layers.Dense(64, activation="relu"))
DL_model.add(layers.Dense(128, activation="relu"))
DL_model.add(layers.Dense(256, activation="relu"))
DL_model.add(layers.Dense(512, activation="relu"))
DL_model.add(layers.Dense(1024, activation="relu"))
DL_model.add(layers.Dense(2048, activation="relu"))
DL_model.add(layers.Dense(4096, activation="relu"))
DL_model.add(layers.Dense(1))


In [ ]:
DL_model.compile(optimizer="adam",loss="mae",metrics=["mae"])

In [21]:
DL_model.fit(feat_np,target_np,epochs=20,validation_split=0.15)

Epoch 1/20
30/30 [==============================] - ETA: 0s - loss: 59.8036 - mae: 59.8036

KeyboardInterrupt: 

In [ ]:
feat[-1],target[-1]

([5, 1, 2022], 91.98)

In [26]:
sample=[[int(encoder.transform(["Jul"])),7,2022]]

In [ ]:
DL_model.predict(sample)

1/1 [==============================] - 0s 128ms/step


array([[122.74982]], dtype=float32)

# MACHINE LEARNING

------------------------------------------------------

In [27]:
from sklearn.linear_model import LinearRegression
ML_model=LinearRegression()
ML_model.fit(x_train,y_train)

LinearRegression()

In [28]:
ML_model.score(x_test,y_test)

0.43053960904827715

In [29]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test,ML_model.predict(x_test))

16.32666992490362

In [30]:
ML_model.predict(sample)

array([108.24098212])

In [31]:
from sklearn.tree import DecisionTreeRegressor
DT_model=DecisionTreeRegressor()
DT_model.fit(x_train,y_train)

DecisionTreeRegressor()

In [32]:
DT_model.score(x_test,y_test)

0.9613519190834153

In [33]:
mean_absolute_error(y_test,DT_model.predict(x_test))

3.8159666273286477

In [34]:
DT_model.predict(sample)

array([92.2725])